export const primaryGenres = [
  "C-Pop",
  "J-Pop",
  "K-Pop",
  "Avant-garde",
  "Blues",
  "Caribbean",
  "Drum and Bass",
  "Classical",
  "Electronic Rock",
  "Electronica",
  "Comedy",
  "Country",
  "Easy Listening",
  "Ambient",
  "Folk",
  "Hip-Hop and Rap",
  "House",
  "Hardcore Electronic",
  "Industrial",
  "Techno",
  "Trance",
  "Holiday",
  "Christian and Gospel",
  "Jazz",
  "Latin",
  "Metal",
  "Electronic",
  "Pop",
  "Punk",
  "R&B and Soul",
  "Rock",
  "Reggae",
  "Soundtracks and Scores",
  "Vocal",
  "New-Age",
  "World"
];

export const subGenres = [
  {
    primaryGenre: "C-Pop",
    secondaryGenres: [
      "C-pop",
      "C-pop (Cantopop)",
      "C-Pop (Mandopop)",
      "C-pop (Hokkien pop)",
      "Chinese Rock",
      "Chinese R&B",
      "Chinese Hip-Hop",
      "Chinese Folk",
    ],
  },
  {
    primaryGenre: "J-Pop",
    secondaryGenres: [
      "Anime",
      "Kayokyoku",
      "Enka",
      "J-pop",
      "Japanese Jazz",
      "J-Rock",
      "Kayōkyoku",
      "J-Synth",
      "J-Ska",
      "J-Punk",
    ],
  },
  {
    primaryGenre: "K-Pop",
    secondaryGenres: [
      "K-pop",
      "Korean Rock",
      "Korean R&B",
      "Korean Hip-Hop",
      "Korean Folk",
      "Trot",
      "T'ong Guitar",
    ],
  },
  {
    primaryGenre: "Avant-garde",
    secondaryGenres: [
      "Experimental",
      "Noise",
      "Harsh Noise",
      "Harsh Noise Wall",
      "Outsider Music",
      "Lo-Fi",
      "Musique Concrète",
      "Electroacoustic",
      "Freestyle",
      "Acousmatic",
      "Computer",
      "Electroacoustic Improvisation",
      "Field Recording",
      "Live Coding",
      "Live Electronics",
      "Soundscape Composition",
      "Tape Music",
      "Modular",
    ],
  },
  {
    primaryGenre: "Blues",
    secondaryGenres: [
      "Acoustic Blues",
      "Blues Shouter",
      "British Blues",
      "Canadian Blues",
      "Classic Blues",
      "Contemporary Blues",
      "Doom Blues",
      "Folk Blues",
      "Dark Blues",
      "African Blues",
      "Blues Rock",
      "Canadian Blues",
      "Chicago Blues",
      "Classic Female Blues",
      "Contemporary R&B",
      "Country Blues",
      "Delta Blues",
      "Detroit Blues",
      "Harmonica Blues",
      "Hokum Blues",
      "Jazz Blues",
      "Jump Blues",
      "Electric Blues",
      "Gospel Blues",
      "Hill Country Blues",
      "Jump Blues",
      "Modern Blues",
      "Kansas City Blues",
      "Louisiana Blues",
      "Memphis Blues",
      "New Orleans Blues",
      "New York Blues",
      "Piano Blues",
      "Piedmont Blues",
      "Punk Blues",
      "Ragtime Blues",
      "Rhythm and Blues",
      "Soul Blues",
      "St. Louis Blues",
      "Swamp Blues",
      "Urban Blues",
      "Vandeville",
      "West Coast Blues",
      "Texas Blues",
      "West Coast Blues",
      "Zydeco",
    ],
  },
  {
    primaryGenre: "Caribbean",
    secondaryGenres: [
      "Baithak Gana",
      "Dancehall",
      "Bouyon",
      "Cadence-lypso",
      "Calypso",
      "Cha-cha-chá",
      "Chutney",
      "Chutney soca",
      "Chutney parang",
      "Compas",
      "Mambo",
      "Merengue",
      "Méringue",
      "Mozambique",
      "Pichakaree",
      "Punta",
      "Punta Rock",
      "Rasin",
      "Rocksteady",
      "Rumba",
      "Ska",
      "Two-tone",
      "Ska punk",
      "Salsa",
      "Son cubano",
      "Songo",
      "Soca",
      "Power Soca",
      "Timba",
      "Twoubadou",
      "Zouk",
      "Dub",
      "Lovers Rock",
      "Ragga",
      "Ragga Jungle",
      "Reggae Fusion",
      "Reggaeton",
    ],
  },
  {
    primaryGenre: "Drum and Bass",
    secondaryGenres: [
      "Darkcore",
      "Liquid Funk",
      "Neurofunk",
      "Drumfunk",
      "Intelligent D&B",
      "Neurohop",
      "Liquid Funk",
      "Neurofunk",
      "Jump-Up",
      "Darkstep",
      "Progressive D&B",
      "Drumstep",
      "Funkstep",
      "Hardstep",
      "Oldschool Jungle",
      "Darkside Jungle",
      "Ragga Jungle",
      "Raggacore",
      "Sambass",
      "Techstep",
    ],
  },
  {
    primaryGenre: "Classical",
    secondaryGenres: [
      "Avant-Garde",
      "Ballet",
      "Baroque",
      "Cantata",
      "Chamber Music",
      "String Quartet",
      "Chant",
      "Choral",
      "Classical Crossover",
      "Concerto",
      "Concerto Grosso",
      "Contemporary Classical",
      "Early Music",
      "Expressionist",
      "High Classical",
      "Impressionist",
      "Mass Requiem",
      "Medieval",
      "Minimalism",
      "Modern Composition",
      "Modern Classical",
      "Opera",
      "Oratorio",
      "Orchestral",
      "Organum",
      "Renaissance",
      "Early Romantic",
      "Later Romantic",
      "Sonata",
      "Symphonic",
      "Symphony",
      "Indian Classical",
      "Hindustani Classical",
      "Wedding Music",
    ],
  },
  {
    primaryGenre: "Electronic Rock",
    secondaryGenres: [
      "Alternative Dance",
      "Synthpunk",
      "Baggy",
      "Madchester",
      "Indietronica",
      "Coldwave",
      "Dance-Rock",
      "Dance-Punk",
      "Dark Wave",
      "Electroclash",
      "Electronicore",
      "Nintendocore",
      "Electropunk",
      "Ethereal Wave",
      "Krautrock",
      "Minimal Wave",
      "New Rave",
      "Nu-Gaze",
      "Space Rock",
      "Synthpop",
      "Synthwave",
      "Chillwave",
      "Cyberpunk",
      "Darksynth",
      "Futurewave",
      "Outrun",
      "Retro Electro",
      "Retrowave",
    ],
  },
  {
    primaryGenre: "Electronica",
    secondaryGenres: [
      "Berlin School",
      "Funktronica",
      "Laptronica",
      "Livetronica",
      "Asian Underground",
      "Worldbeat",
      "Chillwave",
      "Electronic Art Music",
      "Folktronica",
      "Freestyle",
      "Laptronica",
      "Skweee",
      "Sound Art",
      "Synthcore",
    ],
  },
  {
    primaryGenre: "Comedy",
    secondaryGenres: [
      "Comedy Rap",
      "Comedy Pop",
      "Comedy Rock",
      "Novelty",
      "Parody",
      "Stand-Up",
      "Vaudeville",
    ],
  },
  {
    primaryGenre: "Country",
    secondaryGenres: [
      "Alternative Country",
      "Cowpunk",
      "Americana",
      "Australian Country",
      "Bakersfield Sound",
      "Bluegrass",
      "Progressive Bluegrass",
      "Reactionary Bluegrass",
      "Contemporary Bluegrass",
      "Contemporary Country",
      "Blues Country",
      "Cajun",
      "Cajun Fiddle",
      "Christian Country",
      "Classic Country",
      "Close Harmony",
      "Country Gospel",
      "Country Blues",
      "Country Pop",
      "Country Rap",
      "Country Rock",
      "Country Soul",
      "Cowboy/Western",
      "Traditional Bluegrass",
      "Cowboy Pop",
      "Cowpunk",
      "Dansband",
      "Hokum",
      "Honky Tonk",
      "Franco-Country",
      "Gulf and Western",
      "Instrumental Country",
      "Lubbock Sound",
      "Punkabilly",
      "Música Sertaneja",
      "Nashville Sound",
      "Neotraditional Country",
      "Outlaw Country",
      "Progressive Country",
      "Red Dirt",
      "Sertanejo",
      "Rockabilly",
      "Hellbilly",
      "Psychobilly",
      "Texas Country",
      "Traditional Country",
      "Truck-driving Country",
      "Urban Cowboy",
      "Western Swing",
      "Zydeco",
    ],
  },
  {
    primaryGenre: "Easy Listening",
    secondaryGenres: [
      "Background",
      "Bop",
      "Beautiful",
      "Elevator",
      "Furniture",
      "Lounge",
      "Middle of the Road",
      "Swing",
    ],
  },
  {
    primaryGenre: "Ambient",
    secondaryGenres: [
      "Ambient Dub",
      "Ambient House",
      "Ambient Techno",
      "Dark Ambient",
      "Dungeon Synth",
      "Drone",
      "Space",
      "Illbient",
      "Psybient",
      "Lowercase",
      "Isolationism",
    ],
  },
  {
    primaryGenre: "Folk",
    secondaryGenres: [
      "Anti-Folk",
      "American Folk Revival",
      "British Folk Revival",
      "Turbo-Folk",
      "Celtic",
      "Alternative Folk",
      "Irish Folk",
      "Chalga",
      "Filk",
      "Contemporary Folk",
      "Contemporary Singer/Songwriter",
      "Folk Rock",
      "Folktronica",
      "Freak Folk",
      "Chanson",
      "Indie Folk",
      "Industrial Folk",
      "Neofolk",
      "Progressive Folk",
      "Protest Song",
      "Psychedelic Folk",
      "Singer-Songwriter",
      "New Acoustic",
      "Traditional Folk",
      "Skiffle",
      "Sung Poetry",
      "Traditional Folk",
      "Western Music",
      "Techno-Folk",
      "Hong Kong Folk",
      "Vietnamese Folk",
      "Taiwanese Folk",
      "Malaysian Folk",
      "Singaporean Folk",
    ],
  },
  {
    primaryGenre: "Hip-Hop/Rap",
    secondaryGenres: [
      "East Coast",
      "Brick City Club",
      "Mafioso Rap",
      "African Hip-Hop",
      "New Jersey Hip Hop",
      "Dirty South",
      "Cumbia Rap",
      "Breakbeat",
      "UK drill",
      "Avant-Garde Hip-Hop",
      "Alternative Hip-Hop",
      "Australian Hip-Hop",
      "Bongo Flava",
      "Bounce",
      "Country Rap",
      "Boom Bap",
      "Freestyle Rap",
      "British Hip-Hop",
      "Chap-Hop",
      "Chopper",
      "Christian Hip-Hop",
      "Cloud Rap",
      "Conscious Hip-Hop",
      "Crunk",
      "Gangsta Rap",
      "Crunkcore",
      "Drill",
      "Electro",
      "Emo Hip-Hop",
      "Experimental Hip-Hop",
      "G-Funk",
      "Ghetto House",
      "Ghettotech",
      "Golden Age Hip-Hop",
      "Grime",
      "Hardcore Hip-Hop",
      "Hip House",
      "Hiplife",
      "Hip Pop",
      "Hyphy",
      "Industrial Hip-Hop",
      "Instrumental Hip-Hop",
      "Jazz Rap",
      "Jersey Club",
      "Kwaito",
      "Lo-Fi Hip-Hop",
      "West Coast Hip-Hop",
      "Low Bap",
      "Midwest Hip-Hop",
      "Lyrical Hip-Hop",
      "Merenrap",
      "Chicago Hip Hop",
      "Detroit Hip Hop",
      "St. Louis Hip Hop",
      "Twin Cities Hip Hop",
      "Motswako",
      "Mumble Rap",
      "Nerdcore",
      "Turntablism",
      "New Jack Swing",
      "New School Hip-Hop",
      "Old-School Hip-Hop",
      "Latin Rap",
      "Political Hip-Hop",
      "Ragga",
      "Reggaeton",
      "Snap",
      "Jerkin'",
      "Singaporean Hip-Hop",
      "Malaysian Hip-Hop",
      "Hong Kong Hip-Hop",
      "Trap",
      "Trip Hop",
      "Urban Pasifika",
      "Emo Rap",
      "Horrorcore",
      "Underground Rap",
    ],
  },
  {
    primaryGenre: "House",
    secondaryGenres: [
      "Acid House",
      "Ambient House",
      "Balearic Beat",
      "Chicago House",
      "Deep House",
      "Bounce House",
      "Diva House",
      "Scouse House",
      "Hardbag",
      "Disco House",
      "Dream House",
      "Progressive House",
      "Japanese House",
      "Space House",
      "Electro House",
      "Big room House",
      "Complextro",
      "Dutch House",
      "Fidget House",
      "French House",
      "Nu-Disco",
      "Funky House",
      "Future House",
      "Freestyle House",
      "Garage House",
      "Ghetto House",
      "Ghettotech",
      "Minimal House",
      "Juke House",
      "Footwork",
      "Hard House",
      "Hard Dance",
      "Hip House",
      "Italo House",
      "Nu-Jazz",
      "Kidandali",
      "Kwaito",
      "Rave Music",
      "Swing House",
      "Latin House",
      "Microhouse",
      "Moombahton",
      "Moombahcore",
      "Progressive House",
      "Rara Tech",
      "Tech House",
      "Tribal House",
      "Tropical House",
      "Witch House",
      "UK Hard House",
      "US Garage",
      "Vocal House",
      "Jackin House",
    ],
  },
  {
    primaryGenre: "Hardcore Electronic",
    secondaryGenres: [
      "Bouncy House",
      "Gabber",
      "4-Beat",
      "Breakbeat Hardcore",
      "Bouncy Techno",
      "Breakcore",
      "Doomcore",
      "Hardbass",
      "Digital Hardcore",
      "Darkcore",
      "Industrial Hardcore",
      "Happy Hardcore",
      "Mákina",
      "Speedcore",
      "Hard NRG",
      "Splittercore",
      "Extratone",
      "UK Hardcore",
      "Nightcore",
      "Hard Dance",
      "Hardstyle",
      "Dubstyle",
      "Jumpstyle",
      "Lento Violento",
      "Rawstyle",
      "Terrorcore",
      "UK Hardcore",
    ],
  },
  {
    primaryGenre: "Industrial",
    secondaryGenres: [
      "Aggrotech",
      "Coldwave",
      "Cybergrind",
      "Death Industrial",
      "Electro-Industrial",
      "Electrogrind",
      "Dark Electro",
      "Electronic Body",
      "Futurepop",
      "New Beat",
      "Industrial Metal",
      "Noise",
      "Power Noise",
      "Industrial Rock",
      "Japanoise",
      "Neue Deutsche Härte",
      "Power Electronics",
      "Death Industrial",
      "Power Noise",
    ],
  },
  {
    primaryGenre: "Techno",
    secondaryGenres: [
      "Acid Techno",
      "Free Tekno",
      "Ghettotech",
      "Detroit Techno",
      "Minimal",
      "Schranz",
      "Techno-D&B",
      "Hardtechno",
      "Progressive Techno",
      "Industrial Techno",
      "Minimal Techno",
      "Nortec",
      "Technopop",
      "Tecno Brega",
      "Toytown Techno",
    ],
  },
  {
    primaryGenre: "Trance",
    secondaryGenres: [
      "Acid Trance",
      "Classic Trance",
      "Dream Trance",
      "Balearic Trance",
      "Dark Psytrance",
      "Full-On",
      "Dream Trance",
      "Euro-Trance",
      "Hard Trance",
      "Goa Trance",
      "Nitzhonot",
      "Progressive Trance",
      "Psybreaks",
      "Psyprog",
      "Suomisaundi",
      "Psychedelic Trance",
      "Full-On",
      "Suomisaundi",
      "Goa Trance",
      "Progressive Trance",
      "Tech Trance",
      "Orchestral Trance",
      "Uplifting Trance",
      "Vocal Trance",
    ],
  },
  {
    primaryGenre: "Holiday",
    secondaryGenres: [
      "Chanukah",
      "Christmas (Children’s)",
      "Christmas (Classic)",
      "Christmas (Classical)",
      "Christmas (Comedy)",
      "Christmas (Jazz)",
      "Christmas (Modern)",
      "Christmas (Pop)",
      "Christmas (R&B)",
      "Christmas (Religious)",
      "Christmas (Rock)",
      "Easter",
      "Halloween",
      "Other",
      "Thanksgiving",
    ],
  },
  {
    primaryGenre: "Christian and Gospel",
    secondaryGenres: [
      "Contemporary Christian",
      "Christian Metal",
      "Christian Pop",
      "Christian Rap",
      "Christian Rock",
      "Classic Christian",
      "Contemporary Gospel",
      "Gospel",
      "Praise & Worship",
      "Qawwali",
      "Southern Gospel",
      "Traditional Gospel",
    ],
  },
  {
    primaryGenre: "Jazz",
    secondaryGenres: [
      "Acid Jazz",
      "Afro-Cuban Jazz",
      "Avant-garde Jazz",
      "Big Band",
      "Bebop",
      "Blue Note",
      "Boogie-Woogie",
      "Bossa Nova",
      "British Dance Band",
      "Cape Jazz",
      "Chamber Jazz",
      "Continental Jazz",
      "Contemporary Jazz",
      "Cool Jazz",
      "Crossover Jazz",
      "Dixieland",
      "Ethno Jazz",
      "Ethio-jazz",
      "European Free Jazz",
      "Free Funk",
      "Free Improvisation",
      "Free Jazz",
      "Gypsy Jazz",
      "Hard Bop",
      "Jazz Blues",
      "Jazz-Funk",
      "Jazz Fusion",
      "Jazz Rap",
      "Indian Jazz",
      "Jazz Rock",
      "Kansas City Blues",
      "Kansas City Jazz",
      "Latin Jazz",
      "Livetronica",
      "Lo-Fi",
      "Hard Bop",
      "M-Base",
      "Mainstream Jazz",
      "Modal Jazz",
      "Neo-bop Jazz",
      "Neo-Swing",
      "Novelty Ragtime",
      "Nu-Jazz",
      "Mainstream Jazz",
      "Orchestral Jazz",
      "Post-Bop",
      "Progressive Jazz",
      "Psychedelic Jazz",
      "Punk Jazz",
      "Ragtime",
      "Shibuya-Kei",
      "Ska Jazz",
      "Smooth Jazz",
      "Soul Jazz",
      "Stride Jazz",
      "Straight-ahead Jazz",
      "Swing",
      "Third Stream",
      "Trad Jazz",
      "Vocal Jazz",
      "West Coast Jazz",
    ],
  },
  {
    primaryGenre: "Latin",
    secondaryGenres: [
      "Axé",
      "Brazilian Rock",
      "Alternativo",
      "Rock Latino",
      "Brega",
      "Tecnobrega",
      "Choro",
      "Latin Jazz",
      "Forró",
      "Raíces",
      "Punta",
      "Punta Rock",
      "Raison",
      "Soca",
      "Son Cubano",
      "Regional Mexicano",
      "Frevo",
      "Funk Carioca",
      "Lambada",
      "Maracatu",
      "Música Popular Brasileira",
      "Tropicalia",
      "Música Sertaneja",
      "Toná",
      "Martinetes",
      "Tonás",
      "Soleás",
      "Bulerías",
      "Alegrías",
      "Caracoles",
      "Peteneras",
      "Fandangos",
      "Tango",
      "Cantes de Ida y Vuelta",
      "Samba",
      "Pagode",
      "Merengue Típico",
      "Samba Rock",
      "Latin Christian",
      "Nuevo Flamenco",
      "Latin Jazz",
      "Afro-Cuban Jazz",
      "Bossa Nova",
      "Portuguese fado",
      "Tecnobrega",
      "Zouk-Lambada",
      "Zouk",
      "Pop Latino",
      "Latin Ballad",
      "Rock en Español",
      "Reggaeton",
      "Latin Trap",
      "Banda",
      "Grupera",
      "Mariachi",
      "Ranchera",
      "Norteño",
      "Tejano",
      "Traditional",
      "Bullerengue",
      "Fado",
      "Huayno",
      "Flamenco",
      "Spanish Flamenco",
      "Mexican Son",
      "Nueva Canción",
      "Tropicalia",
      "Bachata",
      "Bolero",
      "Criolla",
      "Cumbia",
      "Chicha",
      "Contemporary Latin",
      "Porro",
      "Baladas y Boleros",
      "Guajira",
      "Mambo",
      "Merengue",
      "Cuban Rumba",
      "Salsa",
      "Twoubadou",
      "Salsa Romántica",
      "Son",
      "Timba",
      "Tropipop",
      "Vallenato",
      "Chicano",
      "Classic Tejano",
      "Conjunto",
      "Conjunto Progressive",
      "New Mex",
      "Tex-Mex",
    ],
  },
  {
    primaryGenre: "Metal",
    secondaryGenres: [
      "Alternative Metal",
      "Avant-garde Metal",
      "Black Metal",
      "Symphonic Black Metal",
      "Viking Metal",
      "War Metal",
      "Christian Metal",
      "Hair Metal",
      "Unblack Metal",
      "Death Metal",
      "Death 'n' Roll",
      "Melodic Death Metal",
      "Hardcore",
      "Technical Death Metal",
      "Deathgrind",
      "Doom Metal",
      "African Heavy Metal",
      "Black Doom Metal",
      "Blackened Death-Doom",
      "Death-Doom",
      "Funeral Doom",
      "Drone Metal",
      "Epic Doom",
      "Gothic Doom",
      "Progressive Doom",
      "Modern Metal",
      "Sludge Metal",
      "Stoner Rock",
      "Post Hardcore",
      "Traditional Doom",
      "Epic Metal",
      "Folk Metal",
      "Celtic Metal",
      "Medieval Metal",
      "Pagan Metal",
      "Funk Metal",
      "Glam Metal",
      "Gothic Metal",
      "Pirate Metal",
      "Grindcore",
      "Stoner Metal",
      "Nintendocore",
      "Industrial Metal",
      "Kawaii Metal",
      "Latin Metal",
      "Metalcore",
      "Melodic Metalcore",
      "Heavy Metal",
      "Deathcore",
      "Mathcore",
      "Metalstep",
      "Neoclassical Metal",
      "British Heavy Metal New Wave",
      "Neue Deutsche Härte",
      "Nu-Metal",
      "Math Metal",
      "Taiwanese Metal",
      "Post-Metal",
      "Power Metal",
      "Progressive Metal",
      "Djent",
      "Rap Metal",
      "Speed Metal",
      "Symphonic Metal",
      "Crossover",
      "Thrash Metal",
      "Crossover Thrash",
      "Groove Metal",
    ],
  },
  {
    primaryGenre: "Electronic",
    secondaryGenres: [
      "8-Bit",
      "Club",
      "Club Dance",
      "Breakcore",
      "Brostep",
      "Chillstep",
      "Bubblegum Dance",
      "Post-Disco",
      "Deep House",
      "Dubstep",
      "Electro House",
      "Electroswing",
      "Experimental",
      "Exercise",
      "Future Garage ",
      "Garage",
      "Glitch-Hop",
      "Glitch Pop ",
      "Dancehall",
      "Dub Poetry",
      "Dub Reggae",
      "Dub Techno",
      "Dubstep",
      "Riddim",
      "Dubtronica",
      "Liquid Dub",
      "4-Beat",
      "Acid Breaks",
      "Baltimore Club",
      "Jersey Club",
      "Breakbeat Hardcore",
      "Big Beat",
      "Broken Beat",
      "Florida Breaks",
      "Miami Bass",
      "Nu-Skool Breaks",
      "Grime",
      "Eurobeat",
      "Eurodance",
      "Hard Dance",
      "Italo Dance",
      "Futurepop",
      "Eurodance",
      "Horrorcore",
      "Hi-NRG",
      "Afro/Cosmic",
      "Disco Polo",
      "Euro Disco",
      "4x4 Garage",
      "2-Step Garage",
      "Brostep",
      "Reggaestep",
      "Breakstep",
      "Future Garage",
      "Grime",
      "Grindie",
      "Speed Garage",
      "Bassline",
      "UK Funky",
      "Italo Disco",
      "Nu-Disco",
      "Space Disco",
      "Electronic Dance Music",
      "Intelligent Dance Music",
      "Glitch",
      "Wonky",
      "Ragga Jungle",
      "Raggacore",
      "Acid Jazz",
      "Boogie",
      "City Pop",
      "Chillwave",
      "Vaporwave",
      "Hardvapour",
      "Dance-Pop",
      "Dance-Rock",
      "Chill-Out",
      "New-Age",
      "Trip Hop",
      "Regstep",
      "Trap EDM",
      "Bitpop",
      "Electro Backbeat",
      "Electro-Grime",
      "Electropop",
      "Electro-Industrial",
    ],
  },
  {
    primaryGenre: "Pop",
    secondaryGenres: [
      "Adult Contemporary",
      "Arabic Pop",
      "Baroque Pop",
      "Brill Building",
      "Britpop",
      "Chamber Pop",
      "Bubblegum Pop",
      "Canción",
      "Canzone",
      "Latin Ballad",
      "Chalga",
      "V-Pop",
      "Chanson",
      "Christian Pop",
      "Classical Crossover",
      "Country Pop",
      "Dance Pop",
      "Disco Polo",
      "Europop",
      "Austropop",
      "Pop Rock",
      "Balkan Pop",
      "French Pop",
      "Electropop",
      "Europop",
      "Austropop",
      "Eurobeat",
      "French Pop",
      "Orchestral Pop",
      "Italo Dance",
      "Italo Disco",
      "Laïkó",
      "Latin Pop",
      "Nederpop",
      "Russian Pop",
      "Fado",
      "Folk Pop",
      "Iranian Pop",
      "Indie Pop",
      "Jangle Pop",
      "Lo-Fi",
      "Mexican Pop",
      "New Romantic",
      "Levenslied",
      "Pop Rap",
      "Operatic Pop",
      "Power Pop",
      "L-Pop",
      "Soft Rock",
      "Popera",
      "Pop Punk",
      "Neon Pop",
      "Emo Pop",
      "Pop Soul",
      "Motorpop",
      "P-Pop",
      "OPM",
      "Progressive Pop",
      "Psychedelic Pop",
      "Rebetiko",
      "Schlager",
      "Sophisti-Pop",
      "Space age Pop",
      "Louisiana Swamp Pop",
      "Sunshine Pop",
      "Surf Pop",
      "Swamp Pop",
      "Dream Pop",
      "Synthpop",
      "Teen Pop",
      "Traditional Pop",
      "Turkish Pop",
      "Vispop",
      "Wonky Pop",
      "Worldbeat",
      "Hong Kong Pop",
      "Hong Kong English Pop",
      "Taiwanese Pop",
      "Indian Pop",
      "Malaysian Pop",
      "Singaporean Pop",
      "Indo Pop",
      "Sundanese Pop",
      "Thai Pop",
      "Thai String Pop",
      "Pinoy Pop",
    ],
  },
  {
    primaryGenre: "Punk",
    secondaryGenres: [
      "Anarcho Punk",
      "Britpunk",
      "Afro Punk",
      "Crust Punk",
      "D-Beat",
      "Art Punk",
      "Christian Punk",
      "Deathrock",
      "Digital Hardcore",
      "Folk Punk",
      "Celtic Punk",
      "Cowpunk",
      "Gypsy Punk",
      "Garage Punk",
      "Grindcore",
      "Crustgrind",
      "Noisegrind",
      "Goregrind",
      "Pornogrind",
      "Hardcore Punk",
      "Melodic Hardcore",
      "Post-Hardcore",
      "Spazzcore",
      "Emo",
      "Emo Pop",
      "Emocore",
      "Screamo",
      "Thrashcore",
      "Crossover Thrash",
      "Powerviolence",
      "Horror Punk",
      "Oi!",
      "Pop Punk",
      "Neon Pop",
      "Psychobilly",
      "Queercore",
      "Riot Grrrl",
      "Ska Punk",
      "Skate Punk",
      "Steampunk",
      "Street Punk",
    ],
  },
  {
    primaryGenre: "R&B/Soul",
    secondaryGenres: [
      "Contemporary R&B",
      "Disco",
      "Funk",
      "Deep Funk",
      "Freestyle",
      "Go-Go",
      "P-Funk",
      "Post-Disco",
      "Boogie",
      "Malaysian R&B",
      "Hong Kong R&B",
      "Singaporean R&B",
      "Alternative R&B",
      "Vietnamese R&B",
      "New Jack Swing",
      "Rhythm and Blues",
      "Soul",
      "Blue-Eyed soul",
      "Northern Soul",
      "Neo Soul",
      "Psychedelic Soul",
      "Southern Soul",
    ],
  },
  {
    primaryGenre: "Rock",
    secondaryGenres: [
      "Alternative Rock",
      "Britpop",
      "Anatolian Rock",
      "College Rock",
      "Post-Britpop",
      "Shoegaze",
      "American Traditional Rock",
      "Grunge",
      "Post-Grunge",
      "Acid Rock",
      "Adult-Oriented Rock",
      "Indie Rock",
      "Raga Rock",
      "Taiwanese Rock",
      "Hong Kong Rock",
      "Sufi Rock",
      "Indian Rock",
      "Malaysian Rock",
      "Singaporean Rock",
      "Dunedin Sound",
      "Arena Rock",
      "Math Rock",
      "Post-Punk Revival",
      "Sadcore",
      "British Invasion",
      "Cock Rock",
      "Slowcore",
      "Jam Band",
      "Beat",
      "Roots Rock",
      "Vietnamese Rock",
      "Christian Rock",
      "Blues Rock",
      "Dark Cabaret",
      "Grindcore",
      "Rockabilly",
      "Electronic Rock",
      "Electronicore",
      "Experimental Rock",
      "Art Rock",
      "Acoustic Rock",
      "Industrial Rock",
      "Post-Punk",
      "Gothic Rock",
      "No Wave",
      "Noise Rock",
      "Post-Rock",
      "Post-Metal",
      "Folk Rock",
      "Garage Rock",
      "Glam Rock",
      "Hard Rock",
      "Jazz Rock",
      "New Wave",
      "World Fusion",
      "Paisley Underground",
      "Desert Rock",
      "Pop Rock",
      "Soft Rock",
      "Progressive Rock",
      "Canterbury Scene",
      "Krautrock",
      "New Prog",
      "Rock in Opposition",
      "Space Rock",
      "Psychedelic Rock",
      "Acid Rock",
      "Tex-Mex",
      "Freakbeat",
      "Neo-Psychedelia",
      "Raga Rock",
      "Rap Rock",
      "Rapcore",
      "Rock and Roll",
      "Southern Rock",
      "Stoner Rock",
      "Surf Rock",
      "Visual Kei",
      "Nagoya Kei",
      "Worldbeat",
      "Wrock",
    ],
  },
  {
    primaryGenre: "Reggae",
    secondaryGenres: [
      "2-Tone",
      "Dancehall",
      "Dub",
      "Roots Reggae",
      "Reggae Fusion",
      "Reggae en Español",
      "Spanish Reggae",
      "Reggae 110",
      "Reggae Bultrón",
      "Romantic Flow",
      "Lovers Rock",
      "Raggamuffin",
      "Ragga",
      "Dancehall",
      "Ska",
      "Dub",
      "Rocksteady",
      "Ragga Jungle",
      "Reggaeton",
      "Rocksteady",
    ],
  },
  {
    primaryGenre: "Soundtrack/Score",
    secondaryGenres: [
      "Film Soundtracks",
      "Film Scores",
      "Musicals",
      "Television Soundtracks",
      "Television Scores",
      "Videogame Soundtracks",
      "Videogame Scores",
      "Chiptunes"
    ],
  },
  {
    primaryGenre: "Vocal",
    secondaryGenres: [
      "Spoken Word",
      "A cappella",
      "Barbershop",
      "Cantique",
      "Doo-wop",
      "Gregorian Chant",
      "Standards",
      "Vocal Jazz",
      "Vocal Pop",
    ],
  },
  {
    primaryGenre: "New-Age",
    secondaryGenres: [
      "Environmental",
      "Healing",
      "Meditation",
      "Nature",
      "Relaxation",
      "Travel",
    ],
  },
  {
    primaryGenre: "World",
    secondaryGenres: [
      "Bongo Flava",
      "Fijiri",
      "Khaliji",
      "Liwa",
      "Sawt",
      "Afrobeat",
      "Apala",
      "Benga",
      "Boomba",
      "Bongo Flava",
      "Bikutsi",
      "Cape Jazz",
      "Chimurenga",
      "Congolese rumba",
      "Coupé-Décalé",
      "Fuji",
      "Genge",
      "Highlife",
      "Hiplife",
      "Igbo highlife",
      "Igbo rap",
      "Isicathamiya",
      "Jit",
      "Jùjú",
      "Gqom",
      "Kadongo Kamu",
      "Kizomba",
      "Kuduro",
      "Kwaito",
      "Kwela",
      "Makossa",
      "Maloya",
      "Marabi",
      "Marrabenta",
      "Mbalax",
      "Mbaqanga",
      "Mbube",
      "Morna",
      "Ndombolo",
      "Palm-wine",
      "Raï",
      "Sega",
      "Shangaan electro",
      "Soukous",
      "Kwassa kwassa",
      "Taarab",
      "Zouglou",
      "Baila",
      "Baul",
      "Bhangra",
      "Bhawaiya",
      "Carnatic",
      "Lavani",
      "Ragini",
      "Dangdut",
      "Luk Thung",
      "Luk Krung",
      "Manila Sound",
      "Original Pilipino",
      "Mor lam",
    ],
  },
];
