const GenreActionTypes = {
    SET_CURRENT_GENRE: "SET_CURRENT_GENRE",
    SET_DISPLAY_PROJECT: "SET_DISPLAY_PROJECT",
    SET_GENRE_ARTISTS: "SET_GENRE_ARTISTS",
    SET_CONTENT_INDEX: "SET_CONTENT_INDEX",
    SET_CONTENT_FILTER: "SET_CONTENT_FILTER",
    SET_CONTENT_TIMEFRAME: "SET_CONTENT_TIMEFRAME"
  };
  
  export default GenreActionTypes;