const SearchActionTypes = {
    SET_SEARCH_FIELD: "SET_SEARCH_FIELD",
    SET_SEARCH_INDEX: "SET_SEARCH_INDEX",
    SET_SEARCH_PROJECT_DATA: "SET_SEARCH_PROJECT_DATA",
    SET_SEARCH_PROJECT_IDS: "SET_SEARCH_PROJECT_IDS",
    SET_SEARCH_SONG_DATA: "SET_SEARCH_SONG_DATA",
    SET_SEARCH_SONG_IDS: "SET_SEARCH_SONG_IDS",
    SET_SEARCH_ARTIST_DATA: "SET_SEARCH_ARTIST_DATA",
    SET_SEARCH_ARTIST_IDS: "SET_SEARCH_ARTIST_IDS",
    SET_SEARCH_PLAYLIST_DATA: "SET_SEARCH_PLAYLIST_DATA",
    SET_SEARCH_PLAYLIST_IDS: "SET_SEARCH_PLAYLIST_IDS",
};

export default SearchActionTypes;
